### ISSUE TITLE
split-brain situation using nats v34

### ISSUE THREAD

**Issue by renelehmann** [cloudfoundry/nats-release#23]
Since we are using nats v34 (https://github.com/cloudfoundry/nats-release/releases/tag/v34) we have been run already twice into a split-brain situation within a week and since we have been updated from nats v33.
We are using cf-deployment v13.1.0 with a three node nats cluster and set the properties for nats like the corresponding cf-deployment.yml: 
https://github.com/cloudfoundry/cf-deployment/blob/v13.1.0/cf-deployment.yml

Setup:
Node index 0 with IP 100.106.192.95
Node index 1 with IP 100.106.224.95
Node index 2 with IP 100.106.160.95   <<< in this case the failing node. 

Output nats.stderr.log:
The failing node 2 (with IP 100.106.160.95) tells:
```
2020/06/22 09:26:06.359171 [INF] 100.106.192.95:4223 - rid:2162 - Route connection created
2020/06/22 09:26:15.068311 [INF] 100.106.192.95:4223 - rid:2163 - Route connection created
2020/06/22 09:26:16.210981 [INF] 100.106.192.95:59470 - rid:2165 - Route connection created
2020/06/22 09:26:16.211073 [ERR] 100.106.192.95:59470 - rid:2165 - authorization error
2020/06/22 09:26:16.406824 [INF] 100.106.192.95:4223 - rid:2166 - Route connection created
2020/06/22 09:26:16.798534 [INF] 100.106.224.95:43430 - rid:2168 - Route connection created
```
 
node 0 (with IP 100.106.192.95) tells:
```
2020/06/22 09:26:16.092728 [INF] 100.106.160.95:4223 - rid:1023 - Route connection created
2020/06/22 09:26:17.327084 [ERR] 100.106.160.95:4223 - rid:1023 - Route Error 'Authorization Violation'
2020/06/22 09:26:17.329460 [INF] 100.106.160.95:40292 - rid:1024 - Route connection created
```

node 1 (with IP 100.106.224.95) is telling:
```
2020/06/22 09:26:07.633943 [ERR] Error trying to connect to route: dial tcp 100.106.160.95:4223: i/o timeout
2020/06/22 09:26:16.631768 [INF] 100.106.160.95:4223 - rid:1805 - Route connection created
```

Behaviour:
During the split-brain state the "faulty" node receives no further updates from the nats cluster partners. 
Subscribers registered on that faulty node don't get updates .e.g from routes.

Fixing:
Restart of the faulty nats node index 2.
The other two nodes does this then mention on the log with "Route connection created".

Remarks:
We see a low cpu or memory load on all three nodes.

Questions:
What could be the cause to get into this split-brain situation since this version change from nats v33 to nats v34 (cf-deployment from 12.42.0 to 13.1.0).
What could we do to get more information and what is needed to get closer to find the root cause?
Monitoring is disabled (like cf-deployment suggests). Debug mode is disabled also.

**Comment by ameowlia** [comment]
Hi @renelehmann, 

Thank you for such a detailed and clear issue!

We have other known split brain issues in the past when people were [enabling nats-tls](https://github.com/cloudfoundry/nats-release/blob/develop/example-manifests/ops-files/enable_nats_tls_for_cf.yml), but we thought it was fixed in v34 of nats, so it is strange that you are having this issue. 

1️⃣  Are you enabling nats tls? 

2️⃣  Also, if you could please provide the nats.conf for all of the nats vms when there is a failure occurring. You can get this by ssh-ing onto the nats VM and getting the contents of `/var/vcap/jobs/nats/config/nats.conf`. Please remove any sensitive information.

Thanks,
Amelia and @KauzClay, CF Networking Engineers

**Comment by renelehmann** [comment]
Hi @ameowlia 

 1
We did not enable nats-tls. 
As already mentioned we are align with the property settings on cf-deployment v13.1.0.
This properties regarding activating nats-tls are only changed in a newer (most recent) cf-deployment v13.5.0: 
https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.5.0

 2
On all three nats vms `nats.conf` is configured the same except their own IP addresses:
`net: "100.106.192.95"`  ,   `net: "100.106.224.95"` ,   `net: "100.106.160.95"`
`host: "100.106.192.95"`  , `host: "100.106.224.95"` , `host: "100.106.160.95"`

Configuration on `/var/vcap/jobs/nats/config/nats.conf`  from one of our three nats vms:
```
nats config:
net: "100.106.160.95"
port: 4222
prof_port: 0
monitor_port: 0

debug: false
trace: false
logtime: true

authorization {
  user: "value redacted"
  password: "value redacted"
  timeout: 15
}

cluster {
  host: "100.106.160.95"
  port: 4223

  authorization {
    user: "value redacted"
    password: "value redacted"
    timeout: 15
  }

  routes = [

    nats-route://[value redacted]:[value redacted]@48e128f0-20d8-4edc-9601-51358511022b.nats.service.cf.internal:4223

    nats-route://[value redacted]:[value redacted]@5079bce9-4a5d-4a8a-93d0-78e4493bc006.nats.service.cf.internal:4223

    nats-route://[value redacted]:[value redacted]@2ff25cc2-88b5-419d-b0db-b086281b0ccb.nats.service.cf.internal:4223

  ]
}
```

**Comment by KauzClay** [comment]
Hey @renelehmann ,

Thanks for the config. That looks like what I would expect though...

>nats-route://[value redacted]:[value redacted]@48e128f0-20d8-4edc-9601-51358511022b.nats.service.cf.internal:4223

We solved our original split-brain problem by adding bosh instance-ids to the hostnames of the nats vms so they could be uniquely addressable. I was expecting to not see this, which would explain your problem. Maybe you've encountered a new variation?

One other question, is this config from the faulty nats vm AFTER it was restored? Or was this the config in the faulty state?

**Comment by KauzClay** [comment]
So, I deployed multiple nats vms and mutliple routers on one of our cf-deployment envs (using cf-deployment 13.5.0) and did not see this problem. I did see a few "Error trying to connect to route", although none with a dial timeout. 

Additionally, all routers had matching route tables, and I was able to consistently hit my routes across multiple routers.

That version of cf-deployment uses routing-release 0.201.0, though I don't see that having any impact.

I'm deploying right now with cf-d 13.1.0 to see how it goes.

What did this split-brain problem manifest like for you? Did your routers have differing route tables? Did your routes switch between success and missing route errors as you curled them repeatedly?

**Comment by renelehmann** [comment]
Hi @KauzClay 

Thanks a lot for testing the scenario and further analysis.

Not sure If I get the question correctly about the config state AFTER or during the faulty state.
There was never a change on the nats configuration and is still the same.
We only restarted the failing node. 
For now if we detect an "Auhorization Violation" on one of the members we are going to restart all three cluster nodes one by one. 
 

Regarding gorouter/routing table... an important information was missing so far. 
During the nats "faulty" state it can have an impact with a component called "service-discovery-controller" which is a subscriber of the nats cluster. 
The "service-discovery-controller" is used for the container-2-container service discovery feature and provides the routing information of the cloudfoundry "apps.internal" domain. 
All service-discovery-controller vms (in our case another three different vms) are often connected to the same nats vm and as long this nats vm is up and running. As soon this particular nats vm does not get message updates from partners then some routing information for the container-2-container service discovery are missing. This then results in client errors like "No address associated with hostname".   
We never investigated into the gorouter routing tables during a nats issue and we never got complaints about a routing failure for other domains than the "apps.internal". Maybe the distribution of the routes information for the gorouters behaves different and one "faulty" nats server does not hurt a lot as long the right information is keeping cached.
But of course deleted/updated/new route informations would also be missing on gorouters which are connected to a "faulty" nats vm.


Some observations: (all of theme we don't see a direct relation near to get into a "faulty" nats state yet)
- On the gorouters and within some period of times we see a high amount of "nats-connection-disconnected"/nats-connection-reconnected" log messages.
- On the nats vms and within some period of time we see a high amount of "Route connection created".  


We suspect it could be in connection with an increased message load and the version jump (gnatsd v1.0.4 to v1.4.1).
Which measurements could help us to uncover a problem? 
Could activating the NATS "monitoring" help us more in that direction and if yes how should we configure it to not expose the monitoring port to everyone?

**Comment by mcwumbly** [comment]
Hi @renelehmann - @jenspinney and I were taking another look at this issue today, and chatted with @KauzClay a bit as well.

We are a still unsure what exactly might be causing your issue, but have a few additional questions:

1. We are not sure what we'd be looking for in debug logs or on the monitoring endpoints. We did turn these on ourselves and poked around a bit. It's possible something will jump out to your or us in these logs when you see the issue, but since we can't reproduce it, we're not sure up front what to look our for.
2. We doubt this is related to the change from v33 to v34, though your point about the version bump to gnatsd is worth noting. We considered suggesting that you roll back to v33 to verify, but v33 has known issues, so that is not recommended.
3. How often does this happen? Since reporting this, how many times have you see this reoccur?
4. Is it always the same node that is faulty? if so, perhaps it would be worth trying a `bosh recreate` on that node?
5. Could you explain a bit more about this part? how are you checking whether nodes are receiving updates?
   > During the split-brain state the "faulty" node receives no further updates from the nats cluster partners.
   > Subscribers registered on that faulty node don't get updates .e.g from routes.
6. Finally, we noticed the `authorization error` and `Authorization Failed` messages in the logs in your initial report. We were able to force the `authorization error` message to print by configuring one nats node with an incorrect password, (but we didn't see the corresponding `Authorization Failed` message anywhere). But it is confusing what could cause that error aside from misconfiguration and at a time other than startup.  Something else may be going on here (it does look like some changes were made in the NATS around auth between the versions you noted, but nothing jumps out to us yet). In the meantime, perhaps it's worth double-checking that the passwords match in all config files.

**Comment by renelehmann** [comment]
Hi @jenspinney and @KauzClay 

Thank you for the time you have taken for the investigations and also the many additional discussion points.

1. Unfortunately we also cannot reproduce it directly.
 After identifying this issue a second time, we recognized the pattern of this "Authorization Violation" to be close enough and determined that we need to monitor it closely and respond to this warning as soon as possible.

2. We thought about the older version to rule out whether we encounter the same problem that we have never noticed before.
So far, however, this has never been a realistic plan.

3. Since 9th of June this three vms got the update along the other components update (from cf 12.42.0 to cf 13.1.0). 
We first encountered the problem on June 11th. Until the 22nd June we didn't detect any malfunction, but there were some errors with no direct effect.
Until today we intervened five times with a restart of the nats server. 

4. This is a good point. Unfortunately the only documented failing node information we have is from the case when we created the issue afterwards.
Looking into the log and to the "Authorization Violation" and "authorization error" error message we see this pattern on all three nodes.
We think the faulty node is the one which logs "autorization error" at the time when another node logs the "Authorization Violation" error.
This was the case on this reported issue (see point 5).
All "Authorization Violation" errors on instance 0 belongs to the IP address of index 2 only. 
The corresponding error "authorization error" on index 2 points to the index 0 instance only.
Index 2 reported always index 1 with "Authorization Violation" only.
Index 1 reported always index 0 only and has the least amount of "Authorization Violation" errors.

All three nats vms run on different availability zones (az) using on-premis hardware with VMware. 
Thinking of an underlying and busy vhost could maybe have an impact. Therefore a recreate could help.
Overall this cloudfoundry environment (Foundation) is used very heavily with around 14'000 apps and around 17'000 routes.

5. When we investigated the issue on 22nd June (concerns this ticket) we used the NATS ruby client.
like: nats-sub -s "nats://xxxxxxx:xxxxxxxx@100.106.192.95:4222" ">" | grep $route
We did this for all three nats servers from another dedicated jumphost and found that a node (index 2) was not receiving the messages.
We noticed that this node did not receive any updates from the partner nodes. 
However, we cannot rule out that if a publisher is connected to a faulty node, the distribution to the partners will still work.
Subscribers who are connected to the "faulty" node do not receive all new messages.
We suspect that if the "faulty" node is the first recipient of a message from a publisher, subscribers will get the updates.

6. The passwords are correct and have been used with the ruby nats-client also.
The error "Authorization Violation" is described with this function:
https://github.com/nats-io/nats-server/blob/v1.4.1/server/client.go#L887-L897

V33: gnatsd v1.0.4 was released on 27 Sep 2017
V34: gnatsd v1.4.1 was released on 8 Feb 2019

**Comment by renelehmann** [comment]
Hi @mcwumbly

Meanwhile we recreated the nats-vm's and still run into this "Authorization Violation" error.
After some days we tripled the amount of cpu and this did not help either. 
The cpu load was around 15-25% before and now below 10%.
After the cpu scale-up we saw then a new monit check failure "Resource limit matched" from this check:
`if totalmem > 500 Mb for 2 cycles then alert`.  
Before the cpu scale-up the memory usage was around 20-30% and afterwards 30-40%.
We then also increased the amount of memory from 2GB to 4GB. But we know the monit check does have the same configuration as before. 
Does this have a reason to set it hard to 500Mb?
`https://github.com/cloudfoundry/nats-release/blob/master/jobs/nats/monit`
  
After all the error "Authorization Violation" does not directly relate to be in a split-brain situation. We always checked some minutes after the error occurred and there was only one situation out of many the distribution to the cluster members did not work.
We see sometimes peaks of cpu usages (maybe 4 times the normal usage) if this "Authorization Violation" errors occur.
We guess that we hit some limitations of nats or something get stuck, which then have side effects like the error we get and the system does run healthy afterwards again. But sometimes it falls into a strange behaviour and keeps there what we declare as a split-brain if the distribution to all cluster members does not work anymore.

We only shortly activated the trace mode and saw like around 1500 message payloads during one second. 
We cannot tell other nats metrics so far, this cloudfoundry foundation has around 700 cell vm's and 54 gorouter's.
We think we have to setup a monitoring for nats metrics and maybe to catch message burst or something like that. 
Could you give us suggestions which metrics are interesting for an evaluation?
Maybe you know already some limitations or can think of? Some information about tuning?

We think about setup a curl request to the localhost on the nats vm itself and collect specific data from the endpoints (varz, subsz, etc.) or watching it closer with e.g. `nats-top` remotely.

**Comment by mcwumbly** [comment]
Hi @renelehmann 

Thanks for continuing to share what you're finding and your hypotheses here. I have read your recent comments, but have not had time to really dig in more deeply again yet. I think we'll need to spend a bit more time reviewing these latest findings and see if we can offer any ideas for next steps.

My immediate thoughts are:

1. If this issue is causing significant operational pain and we suspect it is caused by the latest release, is there a release we feel safe recommending rolling back to? If so, this could alleviate the pain and help us validate that the issue is related to a difference in the two versions of nats-release
2. What can we recommend as far as monitoring for this issue and/or further investigating the root cause? Again, and perhaps especially if this is related to updating the version, it would be great to get to the bottom of it.

If you learn more in the meantime, please keep sharing.

**Comment by KauzClay** [comment]
Hi @renelehmann ,

We have had our hands full lately and haven't had time to dig into this. 

>If this issue is causing significant operational pain and we suspect it is caused by the latest release, is there a release we feel safe recommending rolling back to? If so, this could alleviate the pain and help us validate that the issue is related to a difference in the two versions of nats-release

While v33 isn't recommended, it should be safe to roll back to v32 if you want to give this a go.

Again, if you discover anything else, please share.

Thanks,
Clay & @mcwumbly

**Comment by renelehmann** [comment]
Hi @KauzClay and @mcwumbly 

Meanwhile we have set up the monitoring for the NATS servers. Together with this and the appearance of isolated problems with other components, a network problem (latency) turned out to be the cause of the malfunction.
The situation in the network was analyzed for several days in order to initiate suitable measures and is being monitored further.

Because of this, we don't see any issue with the nats release or the NATS servers themselves. These are reacting very sensitively to the high load and together with the identified network problems.

Thank you very much for your support. So we can close this case.
Best regards, Rene

**Comment by ameowlia** [comment]
Thank you for letting us know!
